  
name: lottery
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: lottery
        run: |
          res=$(node index.js)
          echo $res 
          echo $res > now_awards.txt
          echo "award=$res" >> $GITHUB_ENV
      - name: Read exported variable
        run: |
          echo "${{ env.res }}"
      - name: commit
        uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: now award is ${{ env.award }}